POST http://localhost:8000/foo HTTP/1.1
content-type: application/json

{
    "name": "Francesco",
    "surname": "Luzzi"
}

###

GET  http://localhost:8000/favicon.ico HTTP/1.1


###

GET  http://localhost:8000/foo/ollare?foo=foo HTTP/1.1


###

GET  http://localhost:8000/bar?foo=hello,world&bar=bar HTTP/1.1

###

POST http://localhost:8000/bar HTTP/1.1
content-type: application/json

{
    "foo": "foo",
    "bar": "bar"
}
###

GET http://localhost:8000/multi_params/foo HTTP/1.1

###

GET http://localhost:8000/multi_params/foo/12 HTTP/1.1

